Repository WeBeginners-Community/CSS.Effects-Designs, pull requests merged in 2022-10, with the labels that each got.

#10 Nike logo created using HTML and CSS.
  Logos/Nike Logo/index.html
  Logos/Nike Logo/style.css
Labels: enhancement, hacktoberfest-accepted

#6 Upgraded contribution guidelines making new contributors workflow easy
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 added google logo css art
  Logos/GoggleLogo/index.html
  Logos/GoggleLogo/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#28 Added wiggle-glow-animation
  Css Animations/wiggle-glow-animation/index.html
  Css Animations/wiggle-glow-animation/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 feat-8-CSS_Animated_Waves
  Css Animations/Animated CSS Waves/index.html
  Css Animations/Animated CSS Waves/waves.css
Labels: enhancement, hacktoberfest-accepted

#33 Add game #31
  Games/Demon Fight/game.css
  Games/Demon Fight/index.html
Labels: enhancement, hacktoberfest-accepted

#44 Added Animated Mouse Cursor Animation
  Css Animations/Animated Mouse Cursor/assets/cursor.png
  Css Animations/Animated Mouse Cursor/index.html
  Css Animations/Animated Mouse Cursor/scripts/script.js
  Css Animations/Animated Mouse Cursor/style/style.css
Labels: enhancement, hacktoberfest-accepted

#43 add gitpod
  README.md
Labels: enhancement, hacktoberfest-accepted

#50 Added Glassmorphism Form
  HTML+CSS/Glassmorphism Form/index.html
  HTML+CSS/Glassmorphism Form/style.css
Labels: enhancement, hacktoberfest-accepted

#54 Dropdown Navbar
  Navbars/Dropdown menu/index.html
  Navbars/Dropdown menu/style.css
Labels: enhancement, hacktoberfest-accepted

#69 Santa Claus with snowfall animation in the background added
  Css Animations/Santa-Claus-Snowfall-Animation/index.html
  Css Animations/Santa-Claus-Snowfall-Animation/styles.css
Labels: enhancement, hacktoberfest-accepted

#19 Transparent Navbar
  Navbars/Transparent_Folder/media/blue.webp
  Navbars/Transparent_Folder/navbar1.css
  Navbars/Transparent_Folder/navbar1.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#81 feat-62-Sliced_Text_Effect
  Css Animations/Sliced Text Effect/index.html
  Css Animations/Sliced Text Effect/slice.css
Labels: enhancement, hacktoberfest-accepted

#82 Cool Hover Card
  Css Forms/Cool Hover Card/Readme.md
  Css Forms/Cool Hover Card/index3.html
  Css Forms/Cool Hover Card/marvel.jpg
  Css Forms/Cool Hover Card/style3.css
Labels: enhancement, hacktoberfest-accepted

#76 Created a Landing page
  HTML+CSS/Landing-Page/index.html
  HTML+CSS/Landing-Page/style.css
Labels: enhancement, hacktoberfest-accepted

#20 Animated button using html and css
  Buttons/Animated Button/index.html
  Buttons/Animated Button/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#80 `Page Loading Animation issue #78
  Css Animations/Page Loading Animation/index.html
  Css Animations/Page Loading Animation/style.css
Labels: enhancement, hacktoberfest-accepted

#87 feat-66-confetti_button
  Buttons/Confetti Button/confetti.css
  Buttons/Confetti Button/confetti.css.map
  Buttons/Confetti Button/confetti.scss
  Buttons/Confetti Button/index.html
Labels: enhancement, hacktoberfest-accepted

#83 Typing Speed Tester (Game) added
  Games/Typing Speed Tester (Game)/index.html
  Games/Typing Speed Tester (Game)/js/para.js
  Games/Typing Speed Tester (Game)/js/script.js
  Games/Typing Speed Tester (Game)/style.css
Labels: enhancement, hacktoberfest-accepted

#77 Buttons for #58
  Buttons/Cyber_button/index.html
  Buttons/Cyber_button/style.css
Labels: enhancement, hacktoberfest-accepted

#94 Added Heartbeat animation using CSS
  Css Animations/Heartbeat Animation/index.html
  Css Animations/Heartbeat Animation/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added the Custom Ice Cream Maker in the Games Section
  Games/Custom-IceCream-Maker/index.html
  Games/Custom-IceCream-Maker/script.js
  Games/Custom-IceCream-Maker/styles.css
Labels: enhancement, hacktoberfest-accepted

#93 simple Login Form
  Css Forms/Simple_login_form/index.css
  Css Forms/Simple_login_form/index.html
Labels: enhancement, hacktoberfest-accepted

#56 added side navbar
  Navbars/Navbar_side1/index.html
  Navbars/Navbar_side1/style.css
Labels: enhancement, hacktoberfest-accepted

#13 form validation
  Css Forms/JS Form Validation/form.css
  Css Forms/JS Form Validation/form.js
  Css Forms/JS Form Validation/form_validation.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#105 Subrata Rajak's Contribution: Added the template of a animated button
  Buttons/Bubble Coloring Button/index.html
  Buttons/Bubble Coloring Button/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#99 Cool Login & Signup Page
  HTML+CSS/Cool Signup Login Page/README.md
  HTML+CSS/Cool Signup Login Page/login.css
  HTML+CSS/Cool Signup Login Page/login.html
Labels: enhancement, hacktoberfest-accepted

#101 Added Simon Game
  Games/Simon Game/README.md
  Games/Simon Game/game.js
  Games/Simon Game/images/background.jpg
  Games/Simon Game/index.html
  Games/Simon Game/sounds/blue.mp3
  Games/Simon Game/sounds/green.mp3
  Games/Simon Game/sounds/red.mp3
  Games/Simon Game/sounds/wrong.mp3
  Games/Simon Game/sounds/yellow.mp3
  Games/Simon Game/styles.css
Labels: enhancement, hacktoberfest-accepted

#107 Added css animation buttons
  Buttons/CSS animated button/index.html
  Buttons/CSS animated button/style.css
Labels: enhancement, hacktoberfest-accepted

#108 added animated penguin
  Css Animations/Animated Penguin/index.html
  Css Animations/Animated Penguin/styles.css
Labels: enhancement, hacktoberfest-accepted

#112 Uploaded the code files for Roll-Race
  Games/Roll-Race/README.md
  Games/Roll-Race/forest.ico
  Games/Roll-Race/images/bg-bottom.png
  Games/Roll-Race/images/bg.png
  Games/Roll-Race/images/dice/dice1.png
  Games/Roll-Race/images/dice/dice2.png
  Games/Roll-Race/images/dice/dice3.png
  Games/Roll-Race/images/dice/dice4.png
  Games/Roll-Race/images/dice/dice5.png
  Games/Roll-Race/images/dice/dice6.png
  Games/Roll-Race/images/path/path-1.png
  Games/Roll-Race/images/path/path-null.png
  Games/Roll-Race/images/path/path0.png
  Games/Roll-Race/images/path/path1.png
  Games/Roll-Race/images/path/path2.png
  Games/Roll-Race/images/path/path3.png
  Games/Roll-Race/images/path/path4.png
  Games/Roll-Race/images/path/path5.png
  Games/Roll-Race/images/path/path6.png
  Games/Roll-Race/images/path/path7.png
  Games/Roll-Race/images/path/path8.png
  Games/Roll-Race/images/path/pathvictory.png
  Games/Roll-Race/images/red-dice.png
  Games/Roll-Race/index.html
  Games/Roll-Race/index.js
  Games/Roll-Race/style.css
Labels: enhancement, hacktoberfest-accepted

#123 Typewriter effect.
  Css Animations/typewriter-text/Images/literature.png
  Css Animations/typewriter-text/typewriter.css
  Css Animations/typewriter-text/typewriter.html
Labels: enhancement, hacktoberfest-accepted

#121 Added animated Submit button
  Buttons/Animated Submit Button/README.md
  Buttons/Animated Submit Button/button.css
  Buttons/Animated Submit Button/button.js
  Buttons/Animated Submit Button/index.html
Labels: enhancement, hacktoberfest-accepted

#114 Add Linktree Alternative with Pro Features (HTML+CSS)
  HTML+CSS/Linktree Alternative (Pro Features)/bg.jpg
  HTML+CSS/Linktree Alternative (Pro Features)/bg.png
  HTML+CSS/Linktree Alternative (Pro Features)/index.html
  HTML+CSS/Linktree Alternative (Pro Features)/myimg.png
  HTML+CSS/Linktree Alternative (Pro Features)/style.css
Labels: enhancement, hacktoberfest-accepted

#113 Adde Neumorphism-social-icons
  HTML+CSS/Neumorphism-design/index.html
  HTML+CSS/Neumorphism-design/style.css
Labels: enhancement, hacktoberfest-accepted

#53 added css cards section
  HTML+CSS/Css Cards Section/images/avatar.jpg
  HTML+CSS/Css Cards Section/index.html
  HTML+CSS/Css Cards Section/style.css
  HTML+CSS/CssCardsSection/images/avatar.jpg
  HTML+CSS/CssCardsSection/index.html
  HTML+CSS/CssCardsSection/style.css
Labels: enhancement, hacktoberfest-accepted

#122 Added form wave animation
  8.Form wave animation/index.html
  8.Form wave animation/script.js
  8.Form wave animation/style.css
Labels: enhancement, hacktoberfest-accepted

#132 Glassmorphisim CSS Cool looking Data Science Landing Page
  Landing Pages/Data Science/README.md
  Landing Pages/Data Science/css/login.css
  Landing Pages/Data Science/css/style.css
  Landing Pages/Data Science/css/temp.md
  Landing Pages/Data Science/images/1-a.png
  Landing Pages/Data Science/images/1.png
  Landing Pages/Data Science/images/3.jpg
  Landing Pages/Data Science/images/domain.png
  Landing Pages/Data Science/images/logo.png
  Landing Pages/Data Science/images/temp.md
  Landing Pages/Data Science/index.html
  Landing Pages/Data Science/login.html
  Landing Pages/Data Science/main.js
  Landing Pages/Readme.md
Labels: enhancement, hacktoberfest-accepted

#136 Confused landing page
  HTML+CSS/Confused-design/images/confused (1).jpg
  HTML+CSS/Confused-design/index.html
  HTML+CSS/Confused-design/style.css
Labels: enhancement, hacktoberfest

#148 Anchor-Hover-Animation files added
  Css Animations/Anchor Hover Animation/index.html
  Css Animations/Anchor Hover Animation/style.css
Labels: duplicate, hacktoberfest-accepted

#143 Added Digital Marketing Landing Page
  Landing Pages/Digital Marketing Landing Page/assets/css/bootstrap.min.css
  Landing Pages/Digital Marketing Landing Page/assets/css/flex-slider.css
  Landing Pages/Digital Marketing Landing Page/assets/css/font-awesome.css
  Landing Pages/Digital Marketing Landing Page/assets/css/templatemo-softy-pinko.css
  Landing Pages/Digital Marketing Landing Page/assets/fonts/Flaticon.woff
  Landing Pages/Digital Marketing Landing Page/assets/fonts/FontAwesome.otf
  Landing Pages/Digital Marketing Landing Page/assets/fonts/flexslider-icon.eot
  Landing Pages/Digital Marketing Landing Page/assets/fonts/flexslider-icon.svg
  Landing Pages/Digital Marketing Landing Page/assets/fonts/flexslider-icon.ttf
  Landing Pages/Digital Marketing Landing Page/assets/fonts/flexslider-icon.woff
  Landing Pages/Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.eot
  Landing Pages/Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.svg
  Landing Pages/Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.ttf
  Landing Pages/Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.woff
  Landing Pages/Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.woff2
  Landing Pages/Digital Marketing Landing Page/assets/fonts/slick.eot
  Landing Pages/Digital Marketing Landing Page/assets/fonts/slick.svg
  Landing Pages/Digital Marketing Landing Page/assets/fonts/slick.ttf
  Landing Pages/Digital Marketing Landing Page/assets/fonts/slick.woff
  Landing Pages/Digital Marketing Landing Page/assets/images/banner-bg.png
  Landing Pages/Digital Marketing Landing Page/assets/images/blog-item-01.png
  Landing Pages/Digital Marketing Landing Page/assets/images/blog-item-02.png
  Landing Pages/Digital Marketing Landing Page/assets/images/blog-item-03.png
  Landing Pages/Digital Marketing Landing Page/assets/images/circle-dec.png
  Landing Pages/Digital Marketing Landing Page/assets/images/featured-item-01.png
  Landing Pages/Digital Marketing Landing Page/assets/images/fun-facts-bg.png
  Landing Pages/Digital Marketing Landing Page/assets/images/left-image.png
  Landing Pages/Digital Marketing Landing Page/assets/images/logo.png
  Landing Pages/Digital Marketing Landing Page/assets/images/right-image.png
  Landing Pages/Digital Marketing Landing Page/assets/images/testimonial-icon.png
  Landing Pages/Digital Marketing Landing Page/assets/images/work-process-bg.png
  Landing Pages/Digital Marketing Landing Page/assets/images/work-process-item-01.png
  Landing Pages/Digital Marketing Landing Page/assets/js/bootstrap.min.js
  Landing Pages/Digital Marketing Landing Page/assets/js/custom.js
  Landing Pages/Digital Marketing Landing Page/assets/js/imgfix.min.js
  Landing Pages/Digital Marketing Landing Page/assets/js/jquery-2.1.0.min.js
  Landing Pages/Digital Marketing Landing Page/assets/js/jquery.counterup.min.js
  Landing Pages/Digital Marketing Landing Page/assets/js/popper.js
  Landing Pages/Digital Marketing Landing Page/assets/js/scrollreveal.min.js
  Landing Pages/Digital Marketing Landing Page/assets/js/waypoints.min.js
  Landing Pages/Digital Marketing Landing Page/index.html
  Landing Pages/Digital Marketing Landing Page/prepros-6.config
Labels: enhancement, hacktoberfest-accepted

#141 Newton's Cradle Animation
  Css Animations/Newton's Cradle Animation/index.html
  Css Animations/Newton's Cradle Animation/style.css
Labels: enhancement, hacktoberfest-accepted

#160 instagram logo
  Logos/InstagramLogo/index.html
  Logos/InstagramLogo/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#154 New Year Countdown Project
  Designs-Effects/New Year Countdown/Readme.md
  Designs-Effects/New Year Countdown/img.jpg
  Designs-Effects/New Year Countdown/index.html
  Designs-Effects/New Year Countdown/script.js
  Designs-Effects/New Year Countdown/style.css
Labels: enhancement, hacktoberfest-accepted

#157 added scrolling text css animation
  Css Animations/Scrolling-text/index.html
  Css Animations/Scrolling-text/style.scss
Labels: enhancement, hacktoberfest-accepted

#153 Animated Text
  Css Animations/Text Animation/text.css
  Css Animations/Text Animation/text.html
Labels: enhancement, hacktoberfest-accepted

#159 flappy-bird game
  Games/flappy_bird/README.md
  Games/flappy_bird/Screenshot.png
  Games/flappy_bird/animation.css
  Games/flappy_bird/bird.html
  Games/flappy_bird/images/bg.png
  Games/flappy_bird/images/bird.png
  Games/flappy_bird/images/fg.png
  Games/flappy_bird/images/pipeNorth.png
  Games/flappy_bird/images/pipeSouth.png
  Games/flappy_bird/script.js
  Games/flappy_bird/sounds/fly.mp3
  Games/flappy_bird/sounds/score.mp3
Labels: hacktoberfest, hacktoberfest-accepted

#167 Bouncing Ball Animation Created
  Css Animations/Bouncing-Ball/bouncing-ball.html
Labels: hacktoberfest, hacktoberfest-accepted

#165 responsive navbar added
  Navbars/Responsive Navbar/Desktop_View.mp4
  Navbars/Responsive Navbar/Readme.md
  Navbars/Responsive Navbar/index.html
  Navbars/Responsive Navbar/mobile_view.mp4
  Navbars/Responsive Navbar/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#179 responsive footer design
  Footers/Responsive_FooterDesign/design.css
  Footers/Responsive_FooterDesign/index.html
Labels: enhancement, hacktoberfest-accepted

#178 Added css code for Youtube logo
  Logos/youtube/index.html
  Logos/youtube/style.css
Labels: enhancement, hacktoberfest-accepted

#180 Added Jumping Animation Folder
  Css Animations/Jumping Animation/Jumping.jpg
  Css Animations/Jumping Animation/index.html
  Css Animations/Jumping Animation/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#170 Rock-Paper-Scissor Game.html
  Games/Rock-Paper-Scissor Game.html
Labels: hacktoberfest, hacktoberfest-accepted

#185 Feat: Ping-pong Game
  Games/Ping-Pong-Game/index.html
  Games/Ping-Pong-Game/pong.js
  Games/Ping-Pong-Game/sounds/comScore.mp3
  Games/Ping-Pong-Game/sounds/hit.mp3
  Games/Ping-Pong-Game/sounds/userScore.mp3
  Games/Ping-Pong-Game/sounds/wall.mp3
Labels: hacktoberfest, hacktoberfest-accepted

#186 Added Space Animation
  .DS_Store
  Css Animations/.DS_Store
  Css Animations/SpaceAnimation/.DS_Store
  Css Animations/SpaceAnimation/CSS/animations.css
  Css Animations/SpaceAnimation/CSS/style.css
  Css Animations/SpaceAnimation/images/.DS_Store
  Css Animations/SpaceAnimation/images/1873.jpg
  Css Animations/SpaceAnimation/images/2352.jpg
  Css Animations/SpaceAnimation/images/5603526_1876.jpg
  Css Animations/SpaceAnimation/images/Cody.png
  Css Animations/SpaceAnimation/images/LSOn-unscreen.gif
  Css Animations/SpaceAnimation/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#188 Dragon game
  Games/Dragon game/JavaScript Dragon Game/bg.png
  Games/Dragon game/JavaScript Dragon Game/dino.png
  Games/Dragon game/JavaScript Dragon Game/dragon.png
  Games/Dragon game/JavaScript Dragon Game/gameover.mp3
  Games/Dragon game/JavaScript Dragon Game/index.html
  Games/Dragon game/JavaScript Dragon Game/music.mp3
  Games/Dragon game/JavaScript Dragon Game/script.js
  Games/Dragon game/JavaScript Dragon Game/style.css
  Games/bg.png
  Games/dino.png
  Games/dragon.png
  Games/gameover.mp3
  Games/index.html
  Games/music.mp3
  Games/script.js
  Games/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#173 3d-job card
  Css Animations/Job-card 3d/index.html
  Css Animations/Job-card 3d/p.jpg
  Css Animations/Job-card 3d/style.css
Labels: enhancement, hacktoberfest-accepted

#189 Google Assistant Loading
  Css Animations/Google Assistant Loading/index.html
  Css Animations/Google Assistant Loading/style.css
Labels: enhancement, hacktoberfest-accepted

#175 Animated Login-Form added
  Css Forms/Animated Login Form/README.md
  Css Forms/Animated Login Form/index.html
Labels: enhancement, hacktoberfest-accepted

#177 Student BioData Card With CSS
  HTML+CSS/Student_biodata_card/1.jpg
  HTML+CSS/Student_biodata_card/index.html
  HTML+CSS/Student_biodata_card/style.css
Labels: enhancement, hacktoberfest-accepted

#190 Neumorphism Using HTML CSS
  Css Animations/Neumorphism/index.html
  Css Animations/Neumorphism/style.css
Labels: enhancement, hacktoberfest-accepted

#197 EVM-DUMMY MACHINCE
  Designs-Effects/EVM-DUMMY MACHINE/.e
  Designs-Effects/EVM-DUMMY MACHINE/CONG.png
  Designs-Effects/EVM-DUMMY MACHINE/CPI.png
  Designs-Effects/EVM-DUMMY MACHINE/Screenshot (202).png
  Designs-Effects/EVM-DUMMY MACHINE/download (1).png
  Designs-Effects/EVM-DUMMY MACHINE/download.jpg
  Designs-Effects/EVM-DUMMY MACHINE/download.png
  Designs-Effects/EVM-DUMMY MACHINE/images.jpg
  Designs-Effects/EVM-DUMMY MACHINE/index.html
  Designs-Effects/EVM-DUMMY MACHINE/pixel_wbdy4n.png
  Designs-Effects/EVM-DUMMY MACHINE/script.js
  Designs-Effects/EVM-DUMMY MACHINE/style.css
  Designs-Effects/EVM-DUMMY MACHINE/undraw_voting_nvu7.png
Labels: enhancement, hacktoberfest

#208 Added the Animation files.
  Css Animations/Revolving Square Animation/index.html
  Css Animations/Revolving Square Animation/style.css
Labels: enhancement, hacktoberfest-accepted

#202 CSS clock
  Css Animations/CSS clock/Readme.md
  Css Animations/CSS clock/clock-script.js
  Css Animations/CSS clock/clock-stlye.css
  Css Animations/CSS clock/index.html
Labels: enhancement, hacktoberfest-accepted

#207 Added a new Breakout-Game
  Games/breakout/breakout.css
  Games/breakout/breakout.js
  Games/breakout/hit.mp3
  Games/breakout/index.html
  Games/breakout/paddlehit.mp3
  Games/breakout/score.mp3
Labels: hacktoberfest, hacktoberfest-accepted

#211 Added a CSS Animated Counter
  Css Animations/Animated_Counter/index.html
  Css Animations/Animated_Counter/script.js
  Css Animations/Animated_Counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#209 Ballon Game added
  Games/Ballon Game/app.js
  Games/Ballon Game/index.html
  Games/Ballon Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#228 Falling star animation
  Css Animations/Falling Star Animation/index.html
  Css Animations/Falling Star Animation/preview.md
  Css Animations/Falling Star Animation/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#128 added ratingstar files
  Designs-Effects/ratingstar/index.html
  Designs-Effects/ratingstar/script.js
  Designs-Effects/ratingstar/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#224 This is a template portfolio website using html css only..Hope u like it
  HTML+CSS/Template Portfolio Website/images/chillies.png
  HTML+CSS/Template Portfolio Website/images/cloud.png
  HTML+CSS/Template Portfolio Website/images/coding.png
  HTML+CSS/Template Portfolio Website/images/favicon.png
  HTML+CSS/Template Portfolio Website/images/mountain.png
  HTML+CSS/Template Portfolio Website/images/subham.png
  HTML+CSS/Template Portfolio Website/index.html
  HTML+CSS/Template Portfolio Website/styling/style.css
Labels: enhancement, hacktoberfest-accepted

#223 Added a New Navbar
  Navbars/New_Navbar/index.html
  Navbars/New_Navbar/style.css
Labels: enhancement, hacktoberfest-accepted

#222 Created Microsoft Logo in Logos
  Logos/Microsoft Logo/microsoft.html
Labels: enhancement, hacktoberfest-accepted

#219 Add Glassmorphism Button
  Buttons/Glassmorphism Button/index.html
  Buttons/Glassmorphism Button/style.css
Labels: enhancement, hacktoberfest-accepted

#210 added contact-us page using html and css
  HTML+CSS/Contact-us page/images.jpg
  HTML+CSS/Contact-us page/index.html
  HTML+CSS/Contact-us page/styles.css
Labels: enhancement, hacktoberfest-accepted

#206 added new feature in preloader website
  HTML+CSS/frontend_with_preloader/1-modified.png
  HTML+CSS/frontend_with_preloader/favicon-32x32.png
  HTML+CSS/frontend_with_preloader/index.html
  HTML+CSS/frontend_with_preloader/preloaders-gif-6.gif
  HTML+CSS/frontend_with_preloader/style.css
Labels: enhancement, hacktoberfest-accepted

#235 Added a CSS toggle button
  Buttons/Toggle_button/Day-Night Design Toggle button/index.html
  Buttons/Toggle_button/Day-Night Design Toggle button/script.js
  Buttons/Toggle_button/Day-Night Design Toggle button/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#246 Add CSS Form - feat-CSS_Form-Contact_Details
  Css Forms/Contact Details Form/index.html
  Css Forms/Contact Details Form/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#240 Add files via upload
  Css Animations/Animated Running girl/girl.png
  Css Animations/Animated Running girl/index.html
  Css Animations/Animated Running girl/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#119 good view form
  HTML+CSS/Good View Form/index.html
  HTML+CSS/Good View Form/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#156 Fix: linkedin link in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#250 Added footer template
  Footers/Footer for Community Website/README.md
  Footers/Footer for Community Website/footer.css
  Footers/Footer for Community Website/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#248 Personal Portfolio Website Added
  HTML+CSS/Personal Portfolio Website/.DS_Store
  HTML+CSS/Personal Portfolio Website/css/styles.css
  HTML+CSS/Personal Portfolio Website/favicon.ico
  HTML+CSS/Personal Portfolio Website/images/cloud.png
  HTML+CSS/Personal Portfolio Website/images/computer.png
  HTML+CSS/Personal Portfolio Website/images/mountain.png
  HTML+CSS/Personal Portfolio Website/images/p2.jpg
  HTML+CSS/Personal Portfolio Website/index.html
  HTML+CSS/Personal-Portfolio-Website/css/main.css
  HTML+CSS/Personal-Portfolio-Website/favicon.ico
  HTML+CSS/Personal-Portfolio-Website/images/cloud.png
  HTML+CSS/Personal-Portfolio-Website/images/computer.png
  HTML+CSS/Personal-Portfolio-Website/images/mountain.png
  HTML+CSS/Personal-Portfolio-Website/images/p2.jpg
  HTML+CSS/Personal-Portfolio-Website/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#255 added GameOver functionality and more
  Games/flappy_bird/animation.css
  Games/flappy_bird/bird.html
  Games/flappy_bird/script.js
Labels: enhancement, hacktoberfest-accepted

#258 added CSS Timeline Template
  HTML+CSS/CSS Time-Line Template/index.html
  HTML+CSS/CSS Time-Line Template/style.css
Labels: enhancement, hacktoberfest

#259 Added Apple Logo
  Logos/Apple Logo/index.html
  Logos/Apple Logo/style.css
Labels: enhancement, hacktoberfest-accepted

#251 Add Card Flip Animation
  Css Animations/Card Flip on Hover /3dTransform.html
  Css Animations/Card Flip on Hover /imageuse.jpg
Labels: enhancement, hacktoberfest-accepted

#260 Feat-256-website-travel
  Landing Pages/Travel Website/images/arrow.png
  Landing Pages/Travel Website/images/flat-worried-woman-have-list-credit-debts-overdue-bills-girl-reading-letter-from-collection-agency-about-financial-problems-loans-unpaid-tax-calculation-payment-expen.webp
  Landing Pages/Travel Website/images/heroImage.jpg
  Landing Pages/Travel Website/images/logo-white.png
  Landing Pages/Travel Website/images/photo-1598760122223-45f0f18a1bbd.avif
  Landing Pages/Travel Website/index.html
  Landing Pages/Travel Website/style.css
  Landing Pages/Travel Website/style2.css
Labels: enhancement, hacktoberfest

#261 personal--portfolio website added
  HTML+CSS/portfolio--website/index3.html
  HTML+CSS/portfolio--website/script.js
  HTML+CSS/portfolio--website/script.txt
  HTML+CSS/portfolio--website/style.css
Labels: enhancement, hacktoberfest-accepted

#253 title: add new game
  Games/block.io/game.css
  Games/block.io/game.html
  Games/block.io/game.js
Labels: enhancement, hacktoberfest-accepted

#257 JavaScript form validation
  Css Forms/form validation/index.html
  Css Forms/form validation/index.js
  Css Forms/form validation/style.css
Labels: enhancement, hacktoberfest-accepted

#244 Added my css animations website
  Css Animations/css animations/index.html
  Css Animations/css animations/readme.md
  Css Animations/css animations/style.css
  Css Animations/index.html
  Css Animations/style.css
Labels: enhancement, hacktoberfest

#174 character runing
  Css Animations/Character Runing/girl.png
  Css Animations/Character Runing/index.html
  Css Animations/Character Runing/style.css
Labels: enhancement, hacktoberfest-accepted

#285 Add new Preloaders
  Css Loaders/Css Loaders 3/img.png
  Css Loaders/Css Loaders 3/index.html
  Css Loaders/Css Loaders 3/style.css
Labels: enhancement, hacktoberfest-accepted

#283 Add Analog Clock Animation using CSS
  Css Animations/Analog Clock Animation/Analog Clock Animation.gif
  Css Animations/Analog Clock Animation/index.html
  Css Animations/Analog Clock Animation/script.js
  Css Animations/Analog Clock Animation/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#284 Add Text Shadow Effect using CSS
  Css Animations/Text Shadow Effect/Text Shadow Effect.gif
  Css Animations/Text Shadow Effect/index.html
  Css Animations/Text Shadow Effect/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#271 Added responsive navbar
  Navbars/Responsive navbar for portfolio website/README.md
  Navbars/Responsive navbar for portfolio website/index.html
  Navbars/Responsive navbar for portfolio website/navbar.css
  Navbars/Responsive navbar for portfolio website/navbar.js
Labels: hacktoberfest, hacktoberfest-accepted

#278 Add Atom Animation using CSS
  Css Animations/Atom Animation/Atom Animation.gif
  Css Animations/Atom Animation/index.html
  Css Animations/Atom Animation/style.css
Labels: enhancement, hacktoberfest-accepted

#276 Add Water Wave Text Animation using CSS
  Css Animations/Water wave text animation/Water Wave Text Animation.gif
  Css Animations/Water wave text animation/index.html
  Css Animations/Water wave text animation/style.css
Labels: enhancement, hacktoberfest-accepted

#282 Add Newton's Cradle Animation using CSS
  Css Animations/Newton's Cradle/Newton's Cradle Animation.gif
  Css Animations/Newton's Cradle/index.html
  Css Animations/Newton's Cradle/style.css
Labels: enhancement, hacktoberfest-accepted

#288 Added Contact form with CSS animations
  HTML+CSS/Contact Form CSS/index.html
  HTML+CSS/Contact Form CSS/styles.css
Labels: enhancement, hacktoberfest-accepted

#289 Added Netflix Logo
  Logos/Netflix Logo/index.html
  Logos/Netflix Logo/style.css
Labels: enhancement, hacktoberfest-accepted

#290 added fingerprint scanning animation
  Css Animations/Fingerprint scanning animation/README.md
  Css Animations/Fingerprint scanning animation/fingerPrint_01.png
  Css Animations/Fingerprint scanning animation/fingerPrint_02.png
  Css Animations/Fingerprint scanning animation/index.html
  Css Animations/Fingerprint scanning animation/style.css
Labels: enhancement, hacktoberfest-accepted

#291 social media icons
  Css Animations/social media icons/README.md
  Css Animations/social media icons/index.html
  Css Animations/social media icons/style.css
Labels: enhancement, hacktoberfest-accepted

#294 claymorphism-profile-card
  Css Animations/claymorphism-profile-card/README.md
  Css Animations/claymorphism-profile-card/index.html
  Css Animations/claymorphism-profile-card/pic2.jpg
  Css Animations/claymorphism-profile-card/style.css
Labels: enhancement, hacktoberfest-accepted

#286 Glass Website
  Designs-Effects/glass website/img/logo.png
  Designs-Effects/glass website/img/menu.png
  Designs-Effects/glass website/index.html
  Designs-Effects/glass website/other page/forpass.html
  Designs-Effects/glass website/other page/reset.html
  Designs-Effects/glass website/other page/successfully.html
  Designs-Effects/glass website/style.css
Labels: enhancement, hacktoberfest

#254 Added Startup Landing Page
  Landing Pages/Startup Landing Page/CHANGELOG.md
  Landing Pages/Startup Landing Page/dist/css/style.css
  Landing Pages/Startup Landing Page/dist/images/cta-illustration.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-01.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-02.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-03.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-04.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-05.svg
  Landing Pages/Startup Landing Page/dist/images/feature-icon-06.svg
  Landing Pages/Startup Landing Page/dist/images/hero-back-illustration.svg
  Landing Pages/Startup Landing Page/dist/images/hero-top-illustration.svg
  Landing Pages/Startup Landing Page/dist/images/logo.svg
  Landing Pages/Startup Landing Page/dist/images/pricing-illustration.svg
  Landing Pages/Startup Landing Page/dist/js/main.min.js
  Landing Pages/Startup Landing Page/index.html
  Landing Pages/Startup Landing Page/package-sample.json
  Landing Pages/Startup Landing Page/src/images/cta-illustration.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-01.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-02.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-03.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-04.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-05.svg
  Landing Pages/Startup Landing Page/src/images/feature-icon-06.svg
  Landing Pages/Startup Landing Page/src/images/hero-back-illustration.svg
  Landing Pages/Startup Landing Page/src/images/hero-top-illustration.svg
  Landing Pages/Startup Landing Page/src/images/logo.svg
  Landing Pages/Startup Landing Page/src/images/pricing-illustration.svg
  Landing Pages/Startup Landing Page/src/js/main.js
  Landing Pages/Startup Landing Page/src/scss/_normalize.scss
  Landing Pages/Startup Landing Page/src/scss/abstracts/_functions.scss
  Landing Pages/Startup Landing Page/src/scss/abstracts/_include-media.scss
  Landing Pages/Startup Landing Page/src/scss/abstracts/_mixins.scss
  Landing Pages/Startup Landing Page/src/scss/abstracts/_variables.scss
  Landing Pages/Startup Landing Page/src/scss/base/_base.scss
  Landing Pages/Startup Landing Page/src/scss/base/_helpers.scss
  Landing Pages/Startup Landing Page/src/scss/base/_typography.scss
  Landing Pages/Startup Landing Page/src/scss/components/_buttons.scss
  Landing Pages/Startup Landing Page/src/scss/components/_forms.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_cta.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_features.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_footer.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_header.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_hero.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_main.scss
  Landing Pages/Startup Landing Page/src/scss/layout/_pricing.scss
  Landing Pages/Startup Landing Page/src/scss/style.scss
Labels: enhancement, hacktoberfest-accepted

#249 Added Netflix Logo Animation
  Logos/Netflix Logo Animation/index.html
  Logos/Netflix Logo Animation/script.js
  Logos/Netflix Logo Animation/style.css
Labels: enhancement, hacktoberfest-accepted

#295 parallax scrolling website
  Css Animations/Parallax website/README.md
  Css Animations/Parallax website/images/astro.png
  Css Animations/Parallax website/images/img
  Css Animations/Parallax website/images/m_1.png
  Css Animations/Parallax website/images/m_3.png
  Css Animations/Parallax website/index.html
  Css Animations/Parallax website/paralax.js
  Css Animations/Parallax website/style.css
Labels: enhancement, hacktoberfest-accepted

#268 Title: Create a floating label text input #23
  Css Animations/Floating Label Text Input/index.css
  Css Animations/Floating Label Text Input/index.html
  Css Animations/Floating Label Text Input/index.txt
  Floating Label Text Input/index.css
  Floating Label Text Input/index.html
Labels: enhancement, hacktoberfest-accepted

#229 whatsapp logo
  Logos/whatsapp logo/index.html
  Logos/whatsapp logo/style.css
Labels: enhancement, hacktoberfest-accepted

#300 Space Animation with Rocket
  Css Animations/Space_Animation(Shuttle)/images/Earth.png
  Css Animations/Space_Animation(Shuttle)/images/Jupiter.png
  Css Animations/Space_Animation(Shuttle)/images/Neptune.png
  Css Animations/Space_Animation(Shuttle)/images/Shuttle.png
  Css Animations/Space_Animation(Shuttle)/images/Space_bg.jpg
  Css Animations/Space_Animation(Shuttle)/index.css
  Css Animations/Space_Animation(Shuttle)/index.html
  Css Animations/Space_Animation(Shuttle)/index.txt
Labels: enhancement, hacktoberfest-accepted

#263 Added Special Rainbow Effect
  Designs-Effects/Special Rainbow Effect/index.html
  Designs-Effects/Special Rainbow Effect/script.js
  Designs-Effects/Special Rainbow Effect/style.css
Labels: enhancement, hacktoberfest-accepted

#301 add animated navbar
  Navbars/annimated-navbar/index.html
  Navbars/annimated-navbar/style.css
Labels: enhancement, hacktoberfest-accepted
