Repository WeBeginners-Community/CSS.Effects-Designs, pull requests merged in 2023-02, with the labels that each got.

#473 Hover Card
  Css Animations/Hover Card/HOVER_CARD.html
  Css Animations/Hover Card/HOVER_CARD_CSS.css
Labels: Beginner, SWOC 2023

#484 Adding yoghurt website
  HTML+CSS/Yogurt Page/README.md
  HTML+CSS/Yogurt Page/yoghurt.css
  HTML+CSS/Yogurt Page/yoghurt.html
  HTML+CSS/Yogurt Page/yoghurt.js
Labels: Medium, SWOC 2023

#488 coffee maker machine
  Animated Coffee Maker /index.html
  Animated Coffee Maker /style.css
Labels: bug, Beginner, SWOC 2023

#499 Heart animation
  HTML+CSS/Heart Animation/code.js
  HTML+CSS/Heart Animation/index.html
  HTML+CSS/Heart Animation/style.css
  HTML+CSS/heart animation/code.js
  HTML+CSS/heart animation/index.html
  HTML+CSS/heart animation/style.css
Labels: Medium, SWOC 2023

#502 Sticky cards
  HTML+CSS/Sticky Cards/index.html
  HTML+CSS/Sticky Cards/style.css
Labels: Beginner, SWOC 2023

#518 Modern Product Card Using CSS
  HTML+CSS/CSS Product Card/Style.css
  HTML+CSS/CSS Product Card/index.html
Labels: Beginner, SWOC 2023

#482 Flower using HTML and CSS
  Designs-Effects/Flower Design/index.html
  Designs-Effects/Flower Design/style.css
Labels: Beginner, SWOC 2023

#503 feat: issue #497-Add Four Card Feature Section
  HTML+CSS/Four Card Feature Section/images/favicon-32x32.png
  HTML+CSS/Four Card Feature Section/images/icon-calculator.svg
  HTML+CSS/Four Card Feature Section/images/icon-karma.svg
  HTML+CSS/Four Card Feature Section/images/icon-supervisor.svg
  HTML+CSS/Four Card Feature Section/images/icon-team-builder.svg
  HTML+CSS/Four Card Feature Section/index.html
  HTML+CSS/Four Card Feature Section/style.css
Labels: Beginner, SWOC 2023

#520 blooming flowers with falling leaves
  Css Animations/Blooming Flower Animation/index.html
  Css Animations/Blooming Flower Animation/style.css
Labels: Beginner, SWOC 2023

#527 Logo Wall
  Logos/Logo Wall/index.html
  Logos/Logo Wall/index.js
  Logos/Logo Wall/style.css
Labels: Beginner, SWOC 2023

#526 Event Organizer Landing Page
  HTML+CSS/Event Organizer Landing Page/README.md
  HTML+CSS/Event Organizer Landing Page/about1.png
  HTML+CSS/Event Organizer Landing Page/gallery1.png
  HTML+CSS/Event Organizer Landing Page/gallery2.png
  HTML+CSS/Event Organizer Landing Page/gallery3.png
  HTML+CSS/Event Organizer Landing Page/gallery4.png
  HTML+CSS/Event Organizer Landing Page/home3.png
  HTML+CSS/Event Organizer Landing Page/index.html
  HTML+CSS/Event Organizer Landing Page/style.css
Labels: Beginner, SWOC 2023

#530 Added Flipkart Clone to Landing Pages Folder
  CSS Clones/Flipkart clone/cart.png
  CSS Clones/Flipkart clone/flipkart.png
  CSS Clones/Flipkart clone/index.html
  CSS Clones/Flipkart clone/mixer.png
  CSS Clones/Flipkart clone/search.png
  CSS Clones/Flipkart clone/styles.css
Labels: Beginner, SWOC 2023

#417 Neumorphism keyboard
  Designs-Effects/keyboard/index.html
  Designs-Effects/keyboard/style.css
Labels: Beginner, SWOC 2023

#538 Pizza Menu Website
  CSS Website Designs/Pizza Menu/index.html
  CSS Website Designs/Pizza Menu/style.css
Labels: Beginner, SWOC 2023

#553 Added food website to landing page
  Landing Pages/Food Website/images/fb.png
  Landing Pages/Food Website/images/food-truck.png
  Landing Pages/Food Website/images/insta.png
  Landing Pages/Food Website/images/meal-prep-ideas-1.png
  Landing Pages/Food Website/images/meal-prep-ideas-2.png
  Landing Pages/Food Website/images/meal-prep-ideas-3.png
  Landing Pages/Food Website/images/meal-prep-ideas-4.png
  Landing Pages/Food Website/images/meal-prep-ideas-5.png
  Landing Pages/Food Website/images/meal-prep-ideas-6.png
  Landing Pages/Food Website/images/pharmasict-serving-customer-drug-store.png
  Landing Pages/Food Website/images/pizza.png
  Landing Pages/Food Website/images/twitter.png
  Landing Pages/Food Website/index.html
  Landing Pages/Food Website/styles.css
Labels: Beginner, SWOC 2023

#557 Headphones Website
  CSS Website Designs/Headphones Website/images/about-img.jpg
  CSS Website Designs/Headphones Website/images/background-3.jpg
  CSS Website Designs/Headphones Website/images/core.png
  CSS Website Designs/Headphones Website/images/h1.png
  CSS Website Designs/Headphones Website/images/h2.png
  CSS Website Designs/Headphones Website/images/h3.png
  CSS Website Designs/Headphones Website/images/h4.png
  CSS Website Designs/Headphones Website/images/h5.png
  CSS Website Designs/Headphones Website/images/hero-img.png
  CSS Website Designs/Headphones Website/images/image-background 2.jpg
  CSS Website Designs/Headphones Website/index.html
  CSS Website Designs/Headphones Website/main.js
  CSS Website Designs/Headphones Website/style.css
Labels: Beginner, SWOC 2023

#560 Split Landing Page
  Landing Pages/Split Landing Page/index.html
  Landing Pages/Split Landing Page/ps.jpg
  Landing Pages/Split Landing Page/script.js
  Landing Pages/Split Landing Page/style.css
  Landing Pages/Split Landing Page/xbox.jpg
Labels: Beginner, SWOC 2023

#562 Added Random Password Generator
  HTML+CSS/Random Password Generator/custom.css
  HTML+CSS/Random Password Generator/index.html
Labels: Beginner, SWOC 2023

#563 Annoying Phone Number
  Css Animations/Annoying Phone Number/Screenshot 2023-02-12 153241.jpg
  Css Animations/Annoying Phone Number/index.html
  Css Animations/Annoying Phone Number/style.css
Labels: Beginner, SWOC 2023

#568 Add files via upload
  Css Animations/Text Animation/index.html
  Css Animations/Text Animation/style.css
Labels: Beginner, SWOC 2023

#570 Tilting maze game
  HTML+CSS/Tilting Maze Game/index.html
  HTML+CSS/Tilting Maze Game/script.js
  HTML+CSS/Tilting Maze Game/style.css
Labels: Beginner, SWOC 2023

#565 gooey-svg-effect animations
  Css Animations/Gooey SVG Effects/Screenshot 2023-02-19 001826.jpg
  Css Animations/Gooey SVG Effects/index.html
  Css Animations/Gooey SVG Effects/style.css
Labels: Beginner, SWOC 2023

#575 Animated Moving Eye
  Css Animations/Animated Moving Eye/index.html
  Css Animations/Animated Moving Eye/script.js
  Css Animations/Animated Moving Eye/style.css
Labels: Beginner, SWOC 2023

#571 3d image gallery
  HTML+CSS/3D Image Gallery/code.js
  HTML+CSS/3D Image Gallery/index.html
  HTML+CSS/3D Image Gallery/style.css
Labels: Beginner, SWOC 2023

#573 9 Dots animated Navigation
  Css Animations/9 Dots Navigation/index.html
  Css Animations/9 Dots animated Navigation/style.css
Labels: Beginner, SWOC 2023

#580 Css Marquee Logo Wall
  Css Animations/Css Marquee Logo Wall/Screenshot 2023-02-19 002743.jpg
  Css Animations/Css Marquee Logo Wall/index.html
  Css Animations/Css Marquee Logo Wall/style.css
Labels: Beginner, SWOC 2023

#576 Responsive Landing Page Using Bootstrap and CSS
  Landing Pages/Tin Dog/index.html
  Landing Pages/tinDog/css/style.css
  Landing Pages/tinDog/images/TechCrunch.png
  Landing Pages/tinDog/images/bizinsider.png
  Landing Pages/tinDog/images/dog-img.jpg
  Landing Pages/tinDog/images/iphone6.png
  Landing Pages/tinDog/images/lady-img.jpg
  Landing Pages/tinDog/images/mashable.png
  Landing Pages/tinDog/images/tnw.png
Labels: Beginner, SWOC 2023

#587 Sparkle LED button
  Css Animations/Sparkle LED button/index.html
  Css Animations/Sparkle LED button/style.css
Labels: Beginner, SWOC 2023

#583 Animated Sidebar using CSS
  HTML+CSS/Animated Sidebar/index.html
  HTML+CSS/Animated Sidebar/index.js
  HTML+CSS/Animated Sidebar/style.css
Labels: Beginner, SWOC 2023

#529 Pizza Ordering Website Landing page
  Landing Pages/Pizza Website/pizza.css
  Landing Pages/Pizza Website/pizza.html
Labels: Beginner, SWOC 2023

#594 Animated Moving Bus
  Css Animations/Moving Bus Animation/index.html
  Css Animations/Moving Bus Animation/style.css
Labels: Beginner, SWOC 2023

#595 Added tribute page on ratan tata sir
  .DS_Store
  Tribute pages/Ratan Tata/Ratan Tata.jpg
  Tribute pages/Ratan Tata/childhood.jpeg
  Tribute pages/Ratan Tata/index.css
  Tribute pages/Ratan Tata/index.html
  Tribute pages/Ratan Tata/ratan-tata-2.jpeg
  Tribute pages/Ratan Tata/ratan-tata-with-his-grandmother.jpg
Labels: Beginner, SWOC 2023

#597 Motivational Quotes
  Motivational Quotes/card.css
  Motivational Quotes/card.html
Labels: Beginner, SWOC 2023

#598 Coffee shop Website
  CSS Website Designs/COFFE SHOP PROJECT/Readme.md
  CSS Website Designs/COFFE SHOP PROJECT/images/about-banner.png
  CSS Website Designs/COFFE SHOP PROJECT/images/about-img.png
  CSS Website Designs/COFFE SHOP PROJECT/images/blog-1.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/blog-2.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/blog-3.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/feature-icon-1.png
  CSS Website Designs/COFFE SHOP PROJECT/images/gallery-1.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/gallery-2.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/gallery-3.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/gallery-4.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/gallery-5.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/hero-banner.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-1.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-2.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-3.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-4.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-5.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-6.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-bg-logo.png
  CSS Website Designs/COFFE SHOP PROJECT/images/menu-bg.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/service-1.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/service-2.jpg
  CSS Website Designs/COFFE SHOP PROJECT/images/service-3.jpg
  CSS Website Designs/COFFE SHOP PROJECT/index.html
  CSS Website Designs/COFFE SHOP PROJECT/script.js
  CSS Website Designs/COFFE SHOP PROJECT/style.css
Labels: Beginner, SWOC 2023

#601 Twitter Profile Card
  HTML+CSS/Twitter Profile Card/index.html
  HTML+CSS/Twitter Profile Card/style.css
Labels: Beginner, SWOC 2023

#604 Beer animation 404 page not found
  Css Animations/Beer animation 404 page not found/index.html
  Css Animations/Beer animation 404 page not found/style.css
Labels: Beginner, SWOC 2023

#591 Zomato UI Clone using HTML CSS
  CSS Clones/Zomato Clone/index.html
  CSS Clones/Zomato Clone/style.css
Labels: Beginner, SWOC 2023

#608 Vampire Halloween
  Css Animations/Vampire Halloween/index.html
  Css Animations/Vampire Halloween/style.css
  Css Animations/index.html
  Css Animations/style.css
Labels: Beginner, SWOC 2023

#610 Neon Sign Motion Graphic
  Css Animations/Neon Sign Motion Graphic/index.html
  Css Animations/Neon Sign Motion Graphic/style.css
Labels: Beginner, SWOC 2023

#609 Space Balls In Orbit
  Css Animations/Space Balls In Orbit/index.html
  Css Animations/Space Balls In Orbit/style.css
Labels: Beginner, SWOC 2023
